### ISSUE TITLE
SICK laser visual/collision not correct

### ISSUE THREAD

**Issue by athackst** [neobotix/neo_robot_descriptions#1]
I would like to use this description, but the SICK laser visual/collision shapes aren't the appropriate size, shape or in the correct position.  I need these to be correct for path planning of attached manipulator arm.  In particular I am interested in mpo_500

**Comment by Osiron007** [comment]
Hello,

currently our robot models are very basic. The mpo_500 robot description has no SICK laser included yet. You can find some xacro files in neo_robot_descriptions/mpo_500/xacro_macros/
which can be modified for your needs. You can also modify neo_robot_descriptions/mpo_500/mpo_500.urdf directly.

**Comment by athackst** [comment]
Yes, I looked at the xacro_macros, however the location and size/shape of the SICK laser isn't accurate in them.  It currently is a small box at the forward and rear of the base instead of a mounted cylinder of the appropriate size and location.  I could figure it out, but it would be better if it was provided :)

**Comment by athackst** [comment]
So this is a "close -- will not fix" ?

**Comment by neomob** [comment]
Hello,
Our robot platforms are highly customizable. You can choose the type and the position of the sensors attached as well as the size of the platform itself. It is nearly impossible to maintain the model for every setup and only a small number of users need it for their application. This will not really help you further, I know. So please have a look at [this file](http://www.neobotix-roboter.de/fileadmin/files/downloads/Temp/3D-CAD-Model_MPO-500.zip). The archive contains simplified 3D models of your robot platform in delivery condition. If you just need the measurements you can look into the [manual](http://www.neobotix-robots.com/fileadmin/files/downloads/Anleitungen/MPO-500-OperatingManual.pdf) on page 26. I hope that helps.
